# .github/workflows/ci-tests.yml
# Purpose: Run unit tests across multiple Python versions (matrix build).

name: CI - Python Tests (Matrix)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # also test PRs targeting main

jobs:
  test:
    # Keep the job name simple; do not interpolate runner.os to avoid context issues
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false                 # don't cancel others if one version fails
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]  # assignment requirement

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"                # cache pip to speed repeated installs

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        # unittest is built-in; if you add packages later, keep them in requirements.txt
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests
        run: python -m unittest discover -v
